version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      patch:
        patterns:
          - '*'
        update-types:
          - 'patch'
      commitlint:
        patterns:
          - '@commitlint*'
      semantic-release:
        patterns:
          - '@semantic-release*'
          - 'semantic-release'
      typescript-eslint:
        patterns:
          - '@typescript-eslint*'
      types:
        patterns:
          - '@types/*'
      typescript:
        patterns:
          - 'typescript'
          - 'typescript-*'
          - 'ts-*'
